# Use an official Miniconda runtime as a parent image
FROM continuumio/miniconda3

# Set the working directory in the container
WORKDIR /Users/billyli/UCSD/hhh 

# Copy the current directory contents into the container at /usr/src/app
COPY environment_cuda118.yaml /Users/billyli/UCSD/hhh

# Create the environment using the YAML file
RUN conda env create -f environment_cuda118.yaml

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "spanet", "/bin/bash", "-c"]

# The code to run when container is started

