# Use an official Miniconda runtime as a parent image
FROM continuumio/miniconda3

# Set the working directory in the container
WORKDIR /usr/src/app

# Update the package list and install Vim
RUN apt-get update && apt-get install -y vim-gtk

# Download the YAML file
# Replace the URL with the actual URL of your YAML file
RUN wget -O environment.yaml https://raw.githubusercontent.com/Alexanders101/SPANet/master/environment_cuda118.yaml

# Create the environment using the downloaded YAML file
RUN conda env create -f environment.yaml

# Make RUN commands use the new environment
SHELL ["conda", "run", "-n", "spanet", "/bin/bash", "-c"]

# The code to run when container is started
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "spanet", "pip", "install", "git+https://github.com/Alexanders101/SPANet@master", "ray[tune]", "hyperopt"]
