apiVersion: batch/v1
kind: Job
metadata:
  name: hh-job-test-billy-small
  labels:
    jobgroup: hhh-job-test
spec:
  template:
    spec:
      containers:
      - name: testing
        image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
        command:
        - "python"
        args:
        - "-m"
        - "spanet.test"
        - "/hhh-vol/logs/spanet_output/version_2"
        - -tf
        - "/hhh-vol/data/cms/v12/hhh_testing.h5"
        volumeMounts:
        - mountPath: /hhh-vol
          name: hhh-vol
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 16Gi
            cpu: "8"
            nvidia.com/gpu: "1"
          requests:
            memory: 8Gi
            cpu: "4"
            nvidia.com/gpu: "1"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          - https://github.com/cjmikkels/spanet_hh_test
          - -b
          - main
          - --recurse-submodules
          - /opt/repo/hhh
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: hhh-vol
        persistentVolumeClaim:
          claimName: hhh-vol
      restartPolicy: Never
  backoffLimit: 5
